### ISSUE TITLE
app-admin/1password-8.10.30 small issue

### ISSUE THREAD

**Issue by kiwifb** [jaredallard/overlay#3]
First, thanks for maintaining this properly :) I replaced my makeshift install with it.
I noticed while installing 8.10.30 that `/opt/1Password/1Password-HIDHelper` is not present in the tarball and I cannot see anything generating it in the installation procedure. This means that the following two lines in the ebuild currently do nothing
```
  # The binary requires setuid so it may interact with the Kernel keyring facilities
  chmod u+s /opt/1Password/1Password-KeyringHelper
  chmod g+s /opt/1Password/1Password-KeyringHelper
```
This could have been caught with some `|| die` statements at the end of the command. Of course, it could be an upstream mistake that they are missing. This may need checking in the next release.

**Comment by jaredallard** [comment]
Thanks for reporting this! I'll TAL over the weekend!

**Comment by jaredallard** [comment]
It looks like the KeyringHelper is no longer needed, so I'll just remove that!
